
site_name: Subfolio Portable
site_domain: www.subfolio.com

theme: default
directory: directory

access_file: -fbaccess
properties_file: -fbproperties

auth_session: some_random_string
auth_salt: some_random_string

users_yaml_file: users.yml
groups_yaml_file: groups.yml

// 
