# YAML NOTE: Spacing and capitalization is very important

# User must exist in the user.yml file before they can be added to a group
# Create unlimited groups, add unlimited users to a group

staff:
 - jane
 - john
 - etc

clients:
 - apple
 - microsoft
 - etc
