# format
# user:
#  fullname: User Full Name
#  password: user_password
#  admin: true or false

demo:
 fullname: Subfolio Demo User
 password: demo
 admin: false

client:
 fullname: Client Demo User
 password: client
 admin: false