# YAML NOTE: Indentation, spacing and text case are super important.
# This file must be encoded as Unicode (UTF-8) for it to work properly.

# User must exist in the user.yml file before they can be added to a group
# Create unlimited users
# For securing passwords, read the documentation on hashed passwords

johndoe:
 fullname: John Doe
 password: gr8p4ssw0rd
 admin: false

janedoe:
 fullname: Jane Doe
 hashed_password: 34f28698680030c6dc4873ad82eafdf5
 admin: true
