# Main grunt tasks
init:
  description: 'Compiles everything for the first time.'
  tasks:
    - 'icons'
    - 'assets_dev'

default:
  description: 'Compiles assets and watches file directory for changes.'
  tasks:
    - 'assets_dev'
    - 'watch'

dev:
  description: 'Compiles assets and icons without compression for development.'
  tasks:
    - 'clean:all'
    - 'icons'
    - 'assets_dev'

staging:
  description: 'Compiles assets and icons with compression and deploy on staging servers.'
  tasks:
    - 'before_deploy'
    - 'sftp-deploy:staging'

# Sub tasks
icons:
  description: 'Creates icons and fallback pngs.'
  tasks:
    - 'svgmin:all'
    - 'svgcss:all'
    - 'clean:svg_tidy'

assets_dev:
  description: 'Compiles assets without compression'
  tasks:
    - 'sass:dev'
    - 'uglify:dev'
    - 'postcss:all'

before_deploy:
  description: 'Before deployement actions'
  tasks:
    - 'icons'
    - 'clean:staging'
    - 'copy:staging'
    - 'sass:staging'
    - 'uglify:staging'
    - 'postcss:all'
