background_color:         'white'
background_hover_color:   '#f5f5f5'
border_color:             'transparent'   # If you remove the border, remove the margin-top of #content
line_color:               '#ddd'
text_strong_color:        '#1a1a1a'
text_color:               '#333'
text_light_color:         '#666'
text_dimmed_color:        '#999'
link_color:               '#1a1a1a'
flash_color:              'red'
