
site_logo_url: /config/themes/default/images/logos/logo.png
site_logo_width: 256
site_logo_height: 53

replace_underscore_space: true
replace_dash_space: true
display_file_extensions: true
display_file_names_in_gallery: true
display_info: true

listing_mode: list

display_header: true
display_breadcrumb: true
display_navigation:  true
display_send_page: true
display_collapse_header: true
display_tiny_url: false
display_updated_since: true