#
# DOCUMENTS
#

ai:
  extensions: [ai]
  icon: ai
  display: Illustrator File

eps:
  extensions: [eps]
  icon: eps
  display: Postscript File
  
csv:
  extensions: [csv]
  icon: sql
  display: Comma Separated File

dir:
  extensions: [dir]
  icon: dir
  display: Folder

doc:
  extensions: [doc, docx]
  icon: doc
  display: Word Document

img:
  extensions: [gif, png, jpg]
  icon: pic
  display: Image

bmp:
  extensions: [bmp]
  icon: pic
  display: Bitmap Image

tiff:
  extensions: [tiff, tif]
  icon: pic
  display: TIFF Image  

indd:
  extensions: [indd]
  icon: indd
  display: InDesign Document

indb:
  extensions: [indb]
  icon: indd
  display: InDesign Book
  
key:
  extensions: [key]
  icon: key
  display: Keynote Document

  
numbers:
  extensions: [numbers]
  icon: numbers
  display: Numbers Document

pages:
  extensions: [pages]
  icon: pages
  display: Pages Document
  
ppt:
  extensions: [ppt, pptx, pps]
  icon: ppt
  display: Powerpoint Document

psd:
  extensions: [psd]
  icon: psd
  display: Photoshop File

ae:
  extensions: [ae, aep]
  icon: ae
  display: AfterEffect File
  
snd:
  extensions: [mp3, wav]
  icon: snd
  display: Audio File

swf:
  extensions: [swf]
  icon: swf
  display: Flash Movie

txt:
  extensions: [txt]
  icon: txt
  display: Text File

rtf:
  extensions: [rtf]
  icon: txt
  display: Rich Text File
  
vid:
  extensions: [avi, mov, mp4, mpg, mpeg]
  icon: vid
  display: Movie
  
xls:
  extensions: [xls, xlsx]
  icon: xls
  display: Excel Document                

fla:
  extensions: [fla]
  icon: fla
  display: Flash Movie
  
zip:
  extensions: [zip, str, tar, gz]
  icon: zip
  display: Archive

dmg:
  extensions: [dmg]
  icon: dmg
  display: Disc Image
  
dcr:
  extensions: [dcr]
  icon: dcr
  display: Shockwave Movie
  
pdf:
  extensions: [pdf]
  icon: pdf
  display: PDF Document
  
fnt:
  extensions: [fnt, ttf, bmap, afm]
  icon: fnt
  display: Font

suit:
  extensions: [suit]
  icon: fnt
  display: Font Suitcase
  
merlin:
  extensions: [merlin, merlin2]
  icon: merlin
  display: Merlin File

html:
  extensions: [htm, html, rhtml]
  icon: html
  display: HTML File

ase:
  extensions: [ase]
  icon: ase
  display: Adobe Swatch File
  
sql:
  extensions: [sql]
  icon: sql
  display: MySql Dump
  
#
# Enhancers
#

cut:
  extensions: [cut]
  icon: cut
  display: Shortcut

ftr:
  extensions: [ftr]
  icon: ftr
  display: Feature
  
pop:
  extensions: [pop]
  icon: pop
  display: Popup Window

link:
  extensions: [net, link, com, fr, net, org, me, us, biz, mobi, info, es, de]
  icon: net
  display: Internet Location

site:
  extensions: [site]
  icon: site
  display: Mini Site
