# YAML NOTE: Indentation, spacing and text case are super important.
# This file must be encoded as Unicode (UTF-8) for it to work properly.

# NAVIGATION

browsing: "browsing"
indexof: "index of"
sendpage: "send page"
generatetinyurl: "generate tiny url"
collapseheader: "collapse header"
expandheader: "expand header"
parent_directory: "Parent Directory"
previous_directory: "Previous Directory"
next_directory: "Next Directory"
previous: "Previous"
next: "Next"
seealso: "See also:"

# LISTING

filename: "filename"
size: "size"
date: "date"
kind: "kind"
comment: "comment"

emptyfolder: "This folder is empty"

# ACCESS CONTROL

accessdenied: "Access Denied"
loginasadifferentuser: "Log in as a different user"
youdonthaveaccesstothisdirectory: "You don't have access to this directory."

# 404 ERROR

notfound: "The item that you are looking for was not found."
check_url_go_back: "Please check the url or go to the %s for a file listing."

# LOGIN (if applicable)

username: "Username"
password: "Password"
authenticationrequired: "Authentication required"
enter_user_password: "Enter your username and password"
remember_my_login: "Remember my login"
submit: "Submit"
invalid_user_password: "Invalid username or password."
error: "Error"
logout: "logout"
login_complete: "Login complete"
logout_complete: "Logout complete"
login_failed: "Login Failed"

# FOOTER

updated_since: "Updated since:"
last_week: "last week"
last_month: "last month"
my_last_visit: "my last visit"

# DETAIL PAGE

lastmodified: "last modified"
instructions: "Instructions:"
downloadfile: "Download file"
