
site_name: Subfolio Portable
site_logo_url: /config/themes/default/images/logos/logo.png
site_domain: www.subfolio.com

theme: default
directory: directory

access_file: -access
properties_file: -properties

users_yaml_file: users.yml
groups_yaml_file: groups.yml

filekinds_yaml_file: filekinds.yml
language_yaml_file: language.yml

thumbnail_max_filesize: 5

text_rendering: textile

// 
