# YAML NOTE: Indentation, spacing and text case are super important.
# This file must be encoded as Unicode (UTF-8) for it to work properly.

# To change your logo and other interface elements, go to /config/themes/default/options.yml

### YOUR SITE NAME
### Appears in the header and HTML title of the page

site_name: Subfolio 

### YOUR DOMAIN
### Appears in the breadcrumb navigation

site_domain: www.subfolio.com

### YOUR COPYRIGHT
### You must turn it on in your theme options to display

site_copyright: "&copy; 2010 Subfolio — All rights reserved" 

### YOUR WEBSITE META DESCRIPTION
### For search engines

site_meta_description: "Subfolio provides an elegant, practical and customizable web interface to your file system."

### YOUR GOOGLE ANALYTICS CODE
### Remove "#" to activate

# google_analytics_code: "UA-XXXXXX-X" 

### YOUR ACTIVE THEME / CONTENT LOCATION
### To inactivate iphone theme, add "#" before iphone line

theme: default
iphone_theme: iphone
directory: directory

### HIDE LOCKED FOLDERS
### Will hide any folders user doesn't have access to

hide_locked_folders: false

### YOUR MARK-UP LANGUAGE (Textile, Markup or HTML)
### For styling text in enhancer files

text_rendering: textile

### YOUR FILE SIZE CAP - (in MB)
### Thumbnails will not be generated for files larger than cap

thumbnail_max_filesize: 5

### YOUR YAML FILE NAMES
### No changes needed, unless you don't like our naming conventions

users_yaml_file: users.yml
groups_yaml_file: groups.yml
filekinds_yaml_file: filekinds.yml
language_yaml_file: language.yml
access_file: -access
properties_file: -properties
