# YAML NOTE: Indentation, spacing and text case are super important.
# This file must be encoded as Unicode (UTF-8) for it to work properly.

# To change your logo and other interface elements, go to /config/themes/default/options.yml

# GLOBAL SETTINGS

site_name: Subfolio                # appears in the header and HTML title of the page
site_domain: www.subfolio.com      # appears in the breadcrumb navigation
# site_copyright: "© 2009 Subfolio — All rights reserved" 
                                   # change "Subfolio" to your company name and remove "#" to display

site_meta_description: "Subfolio provides an elegant, practical and customizable web interface to your file system."
                                   # change to your meta description for search engine indexing

# google_analytics_code: "UA-XXXXXX-X" 
                                   # remove "#" to display

theme: default                     # name of the active theme
iphone_theme: iphone               # name of the active iphone theme
directory: directory               # location of your content

hide_locked_folders: false         # hide folders a logged in user does not have access to

# YAML FILE NAMES

users_yaml_file: users.yml         # name of YAML file for users
groups_yaml_file: groups.yml       # name of YAML file for groups

filekinds_yaml_file: filekinds.yml # name of YAML file for file kinds
language_yaml_file: language.yml   # name of YAML file for interface language

access_file: -access               # name of the Enhancer file containing folder permissions
properties_file: -properties       # name of the Enhancer file containing folder properties

# CONTENT SETTINGS

text_rendering: textile            # markup language used to render inline text: Textile, Markup or HTML
thumbnail_max_filesize: 5          # file size cap (in MB) before a thumbnail will not be generated
