
site_name: Subfolio Portable
site_domain: www.subfolio.com

theme: default
directory: directory

access_file: -access
properties_file: -properties

auth_session: some_random_string
auth_salt: some_random_string

users_yaml_file: users.yml
groups_yaml_file: groups.yml

filekinds_yaml_file: filekinds.yml
language_yaml_file: language.yml

// 
