background_color:         '#1a1a1a'
background_hover_color:   'black'
border_color:             '#222'
line_color:               '#222'
text_strong_color:        '#1a1a1a'
text_color:               '#bbb'
text_light_color:         '#555'
text_dimmed_color:        '#999'
link_color:               '#00FFFF'
flash_color:              'red'
