back:                 'white'
main_link:            '#1a1a1a'
main_link_hover:      '#1a1a1a'
main_link_back_hover: 'yellow'
line:                 '#f5f5f5'
text_strong:          '#1a1a1a'
text:                 '#333'
text_light:           '#666'
text_dimmed:          '#999'
flash:                'red'

# Optional colors
border:               'transparent'
#gallery_link:         '#1a1a1a'
#gallery_link_hover:   '#1a1a1a'
gallery_back:         '#f5f5f5'
#gallery_back_hover:   'yellow'
#feature_link:          '#1a1a1a'
feature_link_hover:    '#1a1a1a'
#feature_text_hover:   '#999'
feature_back:          'white'
feature_back_hover:    'yellow'
#sub_link:             '#999'
#sub_link_hover:       '#1c7ad5'
sub_link_back_hover:  'yellow'
#back_shift:           '#202020'