# YAML NOTE: Indentation, spacing and text case are super important.
# This file must be encoded as Unicode (UTF-8) for it to work properly.

### FILE NAME OPTIONS (true/false)
### For making file names prettier in the interface

replace_underscore_space: true
replace_dash_space: true
display_file_extensions: true
